### ISSUE TITLE
Can't build on Allegro CL

### ISSUE THREAD

**Issue by macdavid313** [mmaul/clml#11] opened 2016-03-25 20:09 UTC
this error has been reported during compiling:

```
Attempt to take the value of the unbound variable
`CLML.STATISTICS.RAND::W'.
```

**Comment by mmaul** [comment] 2017-03-25 06:05
I have been able to obtain Allegro 10 x86_64 and have fixed issues and verified tests run clean. Can you try confirm, that the issue is resolved?

**Comment by mmaul** [comment] 2017-04-14 00:39
Closing, fixed

**Closed by mmaul** 2017-04-14 00:39 UTC
